// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelGo_final.Data;

namespace TravelGo_final.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200302151730_addtriptable")]
    partial class addtriptable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelGo_final.Model.AddTrip", b =>
                {
                    b.Property<int>("tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("tdetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tprice")
                        .HasColumnType("int");

                    b.Property<string>("tseason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tid");

                    b.ToTable("addTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
